apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: 'https://kubernetes.default.svc'
  source:
    path: app-deploy
    repoURL: 'https://github.com/SerdarYalcin/demo.git'
    targetRevision: HEAD
    directory:
      include: ''
      exclude: dev.yaml
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
