version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY_URL

  build:
    commands:
      - echo "Building the Docker image..."
      - DOCKER_TAG=$(date +%Y%m%d%H%M%S)  # Generate a timestamp as a unique identifier
      - echo "Building $ Tagging the Docker image..."
      - docker build -t $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:$DOCKER_TAG .

  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:$DOCKER_TAG
      - printf '[{"name":"python-web","imageUri":"%s"}]' $ECR_REGISTRY_URL/$ECR_REPOSITORY_NAME:$DOCKER_TAG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
